### PR TITLE
outline: handle texorpdfstring command.

### PR DESCRIPTION
**Pull request by AnessZurba**
## Description
This handles the command `texorpdfstring` in outline titles

## Related issues / Pull Requests
https://github.com/overleaf/overleaf/issues/1037

## Contributor Agreement

- [x] I confirm I have signed the [Contributor License Agreement](https://github.com/overleaf/overleaf/blob/master/CONTRIBUTING.md#contributor-license-agreement)

### CODE REVIEW

**Comment by AnessZurba** [comment]
@das7pad 
Sorry for the ping, but you seem one of the most active contributors to this repo :) 
Can we get someone to review this tiny PR?
It seems like most of the development is happening somewhere else, so nobody is looking at the PRs here :(

**Comment by das7pad** [comment]
Hello @AnessZurba,

Thank you for your contribution! I've let the team know about your suggestion.
Could you take a look at adding a [test for your change](https://github.com/overleaf/overleaf/blob/main/services/web/test/frontend/features/source-editor/languages/latex/latex-outline.test.ts)? 

Greetings,
Jakob

**Comment by das7pad** [comment]
Thanks for adding that test.

> How do I run the tests?

`overleaf/overleaf$ npm ci` followed by `overleaf/overleaf/services/web$ make test_frontend` should run the tests.
It looks like there is a typo in the tests. Can you also fix the typescript warning and prettier formatting (see `overleaf/overleaf/services/web$ make format_fix lint`)?

(Adding a check for `token.node.firstChild?.firstChild` next to your `=== 'Command'` check should do the trick.)

<details>

```
  1) CodeMirror LaTeX-FileOutline
       for labels using texorpdfstring
         should use the text argument as title:

      AssertionError: expected [ { line: 1, …(4) } ] to deeply equal [ { from: +0, to: 30, …(3) } ]
      + expected - actual

         {
           "from": 0
           "level": 4
           "line": 1
      -    "title": "The function f(x) = x^2: Propreties of x."
      -    "to": 113
      +    "title": "The function f(x) = x^2: Properties of x."
      +    "to": 30
         }
       ]
```


```
frontend/js/features/source-editor/utils/tree-operations/outline.ts:93:21 - error TS18047: 'token.node.firstChild' is possibly 'null'.

93       let command = token.node.firstChild.firstChild
                       ~~~~~~~~~~~~~~~~~~~~~

frontend/js/features/source-editor/utils/tree-operations/outline.ts:94:47 - error TS18047: 'command' is possibly 'null'.

94       let commandName = state.doc.sliceString(command.from + 1, command.to)
                                                 ~~~~~~~

frontend/js/features/source-editor/utils/tree-operations/outline.ts:94:65 - error TS18047: 'command' is possibly 'null'.

94       let commandName = state.doc.sliceString(command.from + 1, command.to)
                                                                   ~~~~~~~

frontend/js/features/source-editor/utils/tree-operations/outline.ts:95:27 - error TS18047: 'token.node.firstChild' is possibly 'null'.

95       let textArguments = token.node.firstChild.getChildren('TextArgument')
                             ~~~~~~~~~~~~~~~~~~~~~


Found 4 errors in the same file, starting at: frontend/js/features/source-editor/utils/tree-operations/outline.ts:93
```
</details>

**Comment by AnessZurba** [comment]
ok @das7pad I think everything is correct now. I have to say the tech stack is a bit complicated (especially with wsl thrown into the mix), so I hope I didn't mess anything

**Comment by AnessZurba** [comment]
Hi @das7pad, can you please ask the team to take a look at this PR?

**Comment by das7pad** [comment]
Hello @AnessZurba,

Thank you for your first contribution to Overleaf. We've imported your change and refactored the handling slightly (https://github.com/overleaf/overleaf/commit/77ad90d59a0c90695f6c470e149c9f0418be89d7).

The change is live on overleaf.com and will be included in the upcoming Server Pro and Community Edition 5.2 release.

image


Greetings,
Jakob

**Comment by AnessZurba** [comment]
Yes, I noticed it in the morning
Thank you!

**Pull request merged**
