### PR TITLE
Merge docker-image repository

### PR DESCRIPTION
**Pull request by mserranom**
Merges https://github.com/overleaf/docker-image into this repository, so we have only a single monorepo for Overleaf CE. 

A build of Overleaf CE has been tested successfully.

The full story of the imported repo has been incorporated, hence the large amount of changes. The only changes actually editing content (not just import/move stuff) are:
- https://github.com/overleaf/overleaf/pull/693/commits/f38b52e0f21af52b7150902e875903f3be7fd5ef
- https://github.com/overleaf/overleaf/pull/693/commits/298f67da15544d50a528d308b9512e82dd08bed7
- https://github.com/overleaf/overleaf/pull/693/commits/7e3a51161ad7fe940a670c0020ae8a1428e3319b
- https://github.com/overleaf/overleaf/pull/693/commits/416e8808b3c38ae53757e50bb42e0c2563d62613
- https://github.com/overleaf/overleaf/pull/693/commits/77ec4f26dcd49e8528a1030439e89a92639ec5c4

In order to merge the repos I've used `tomono`: https://github.com/hraban/tomono/blob/58d150ac6e00bc35ce68f5565a436190ad036b7d/tomono.sh

Config file provided to `tomono`:

```
https://github.com/overleaf/docker-image docker-image
```
script:

```
#!/bin/bash

export MONOREPO_NAME=overleaf

rm -rf overleaf
git clone git@github.com:overleaf/overleaf.git

cat tomono-config.txt | ./tomono.sh --continue 
```

@ShaneKilkelly @jdleesmiller could you freeze https://github.com/overleaf/docker-image and make it read only while this is in review? We can archive it later.

### CODE REVIEW

**Comment by ShaneKilkelly** [comment]
I think this makes sense :+1: will get around to a proper review ASAP. Adding @jdleesmiller as a co-reviewer also, to double-check this is in line with longer-term strategy. 

One question jumps to mind: is there anything in this repo that we can now remove? The gruntfile for instance? We could do that in a separate PR if it makes sense. 

We should also think about adding a tag to the repo once the change is merged. (v2.0 or something), to mark the point at which the purpose of the repo changed.

**Comment by mserranom** [comment]
> One question jumps to mind: is there anything in this repo that we can now remove? 

There are changes worth doing, but didn't want to pile more changes on top of this PR

+1 about tagging, good point!

**Comment by jdleesmiller** [comment]
> longer-term strategy

Looks good to me 👍. If we can combine some repos, I think that will help. Using `tomono` to preserve the history is also helpful.

> make it read only while this is in review? We can archive it later.

I think I will go ahead and archive it, since archiving is reversible anyway.

**Comment by jdleesmiller** [comment]
Hmm. Actually, there are quite a few PRs on docker-image. Do we want to merge any of those before doing this?

**Comment by mserranom** [comment]
Good point, will review existing PRs and see what's the best plan of action.

**Comment by mserranom** [comment]
I'm closing this PR, will rais a new one after some PRs in docker-image are merged.

**Comment by mserranom** [comment]
Raised https://github.com/overleaf/overleaf/pull/694 including pending PRs

**Pull request closed without merging**
