### PR TITLE
Add init script to run migrations from web

### PR DESCRIPTION
**Pull request by ShaneKilkelly**
## Description

Add a new init script, which will run the database migrations in the web project, using the appropriate environment tag.

## Related issues / Pull Requests

- Follow on from https://github.com/overleaf/overleaf/pull/910
- Depends on https://github.com/overleaf/web-internal/pull/4303
- Part of https://github.com/overleaf/issues/issues/3229 and https://github.com/overleaf/issues/issues/3253

## Contributor Agreement

- [x] I confirm I have signed the [Contributor License Agreement](https://github.com/overleaf/overleaf/blob/master/CONTRIBUTING.md#contributor-license-agreement)

### CODE REVIEW

**Review by das7pad — COMMENTED** [review]
The old migration script was running after the db check (`99_migrate` vs `98_check_db_access`). This would flag a broken db setup before attempting to run migrations.
WDYT about doing so again?

**Comment by ShaneKilkelly** [comment]
Good point. Renamed :+1:

**Review by das7pad — APPROVED** [review]

**Comment by das7pad** [comment]
You could test this ahead of merging the web PR using a bind mount in the docker-compose config.

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 58240a5..367a58b 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -17,6 +17,7 @@ services:
             - mongo
             - redis
         volumes:
+            - /path/to/dev-environment/web/migrations:/var/www/sharelatex/web/migrations
             - ~/sharelatex_data:/var/lib/sharelatex
             ########################################################################
             ####  Server Pro: Uncomment the following line to mount the docker  ####
```

**Comment by ShaneKilkelly** [comment]
Tested locally with the suggested volume mount, works nicely :+1:

**Pull request merged**
