### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by Soptq**
## Description

Set a default password to Redis default user so that it won't reply a error when checking connection.

## Related issues / Pull Requests

issue #734 

## Contributor Agreement

- [x] I confirm I have signed the [Contributor License Agreement](https://github.com/overleaf/overleaf/blob/master/CONTRIBUTING.md#contributor-license-agreement)

### CODE REVIEW

**Comment by mserranom** [comment]
Thanks for your contribution. 

You've marked that you've signed the contributor agreement, but I can't find your github username in our records. Was there any problem during the process? Perhaps you were using a different account?

**Comment by jdleesmiller** [comment]
I think this is an OK workaround, but setting a weak default password isn't a great pattern --- it basically defeats the change that redis 6 is trying to make.

Another alternative would be to restrict to redis 5 for now by specifying a version in the docker-compose file.

**Comment by BrozzSama** [comment]
It seems you should also add the REDIS_PASSWORD variable, otherwise you cannot open any document since the real time editor uses different parameters.

**Comment by Soptq** [comment]
> Thanks for your contribution.
> 
> You've marked that you've signed the contributor agreement, but I can't find your github username in our records. Was there any problem during the process? Perhaps you were using a different account?

Sorry, I only read the agreement briefly and I must miss some parts of it. Do I need to somehow add my Github username to a database in order to make a PR?

**Comment by Soptq** [comment]
> I think this is an OK workaround, but setting a weak default password isn't a great pattern --- it basically defeats the change that redis 6 is trying to make.
> 
> Another alternative would be to restrict to redis 5 for now by specifying a version in the docker-compose file.

Yes, it is definitely a second way to deal with the issue. In fact, I personally set a `image: redis:5.0.0` instead of doing what my PR does and it works perfectly. Maybe I should close this PR and make a new one that restrict the redis version?

**Comment by Soptq** [comment]
> > I think this is an OK workaround, but setting a weak default password isn't a great pattern --- it basically defeats the change that redis 6 is trying to make.
> > Another alternative would be to restrict to redis 5 for now by specifying a version in the docker-compose file.
> 
> Yes, it is definitely a second way to deal with the issue. In fact, I personally set a `image: redis:5.0.0` instead of doing what my PR does and it works perfectly. Maybe I should close this PR and make a new one that restrict the redis version?

Yeah maybe I should. I will make another PR and close this one.

**Comment by mserranom** [comment]
> Sorry, I only read the agreement briefly and I must miss some parts of it. Do I need to somehow add my Github username to a database in order to make a PR?

In the [Contributor Agreement Documentation](https://github.com/overleaf/overleaf/blob/master/CONTRIBUTING.md#contributor-license-agreement) there's a link you can follow to the form (or [click here](https://docs.google.com/forms/d/e/1FAIpQLSef79XH3mb7yIiMzZw-yALEegS-wyFetvjTiNBfZvf_IHD2KA/viewform?usp=sf_link))

**Comment by Soptq** [comment]
> > Sorry, I only read the agreement briefly and I must miss some parts of it. Do I need to somehow add my Github username to a database in order to make a PR?
> 
> In the [Contributor Agreement Documentation](https://github.com/overleaf/overleaf/blob/master/CONTRIBUTING.md#contributor-license-agreement) there's a link you can follow to the form (or [click here](https://docs.google.com/forms/d/e/1FAIpQLSef79XH3mb7yIiMzZw-yALEegS-wyFetvjTiNBfZvf_IHD2KA/viewform?usp=sf_link))

Thanks!

**Pull request closed without merging**
