### PR TITLE
Hotfix 2.4.2 - fix anon read/write sharing

### PR DESCRIPTION
**Pull request by mserranom**
## Description

Fixes anonymous read/write links by conditionally including `AuthenticationController.requireLogin()` middleware in routers.

### CODE REVIEW

**Review by jdleesmiller — COMMENTED** [review]
Thanks, looks correct.

Is there a reason to use two new and separate patch files here instead of the one in the original support case? Then we'd only need one `COPY` and one `RUN` ([minimize the number of layers](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers) is a best practice).

**Comment by mserranom** [comment]
The only reason to split the patch (and also using `ADD`) is to keep consistency with previous hotfix patches.

Another good reason to prefer the original patch is to make it compatible with the scripted process (applying the patch, then `commit` the image). I'll do the change, hopefully next hotfix patches will follow this approach.

**Comment by mserranom** [comment]
Now using the original patch (will merge squash)

**Review by jdleesmiller — APPROVED** [review]
LGTM, thanks! 👍

**Pull request merged**
