### PR TITLE
Fix the paths in grunt tasks

### PR DESCRIPTION
**Pull request by msimonin**
Update the path to the new directory structure.
They were using the legacy coffeescript structure.

### CODE REVIEW

**Comment by mserranom** [comment]
Thanks @msimonin, this fixes user registration using `grunt user:create-admin`.

**Comment by wixaw** [comment]
hey @mserranom !
Yes i have this error with 2.0.0 (Warning: Task "user@xxx.fr" not found. Use --force to continue.)

**Comment by mserranom** [comment]
Thanks @wixaw, will investigate.

**Comment by msimonin** [comment]
Hey,

I think I got this error when I use the following syntax:
```
grunt user:create-admin --email joe@example.com
```

instead of
```
grunt user:create-admin --email=joe@example.com
```

**Comment by wixaw** [comment]
Hummm I read "Files change" and i see change  "--email user@domain.fr" to "--email=user@domain.fr"

```
 docker-compose exec sharelatex /bin/bash -c "cd /var/www/sharelatex; grunt user:create-admin --email=william.vincent@irit.fr"
Running "user:create-admin" task
using statsd
Set UV_THREADPOOL_SIZE=16
{"name":"default-sharelatex","hostname":"7eaf0b42c210","pid":541,"level":30,"msg":"Using newsletter provider: none","time":"2019-10-10T12:42:17.503Z","v":0}
{"name":"default-sharelatex","hostname":"7eaf0b42c210","pid":541,"level":30,"msg":"using smtp for email","time":"2019-10-10T12:42:17.764Z","v":0}
{"name":"default-sharelatex","hostname":"7eaf0b42c210","pid":541,"level":30,"key":"mongo.UserGetter.getUserByAnyEmail","args":{},"elapsedTime":25,"msg":"[Metrics] timed async method call","time":"2019-10-10T12:42:17.821Z","v":0}
Fatal error: user.save is not a function
```
And with this fatal error, not have admin button in the webapp ( after restart container and logout )

Thanks 
Will

**Comment by mserranom** [comment]
Thanks @wixaw, @msimonin .

I can't reproduce with image `sharelatex/sharelatex:2.0.0`

```
$ docker-compose exec sharelatex /bin/bash -c "cd /var/www/sharelatex; grunt user:create-admin --email=jow@test.com"
Running "user:create-admin" task
using statsd
Set UV_THREADPOOL_SIZE=16
{"name":"default-sharelatex","hostname":"8424a0b957cd","pid":469,"level":30,"msg":"Using newsletter provider: none","time":"2019-10-14T09:36:33.037Z","v":0}
{"name":"default-sharelatex","hostname":"8424a0b957cd","pid":469,"level":40,"msg":"Email transport and/or parameters not defined. No emails will be sent.","time":"2019-10-14T09:36:33.402Z","v":0}
{"name":"default-sharelatex","hostname":"8424a0b957cd","pid":469,"level":30,"key":"mongo.UserGetter.getUserByMainEmail","args":{},"elapsedTime":1,"msg":"[Metrics] timed async method call","time":"2019-10-14T09:36:33.484Z","v":0}
{"name":"default-sharelatex","hostname":"8424a0b957cd","pid":469,"level":30,"key":"mongo.UserGetter.getUserByAnyEmail","args":{},"elapsedTime":47,"msg":"[Metrics] timed async method call","time":"2019-10-14T09:36:33.485Z","v":0}
(node:469) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
{"name":"default-sharelatex","hostname":"8424a0b957cd","pid":469,"level":30,"user_id":"5da441a1d71baf01d58bd526","key":"ip-matched-affiliation-undefined","msg":"sending mark notification as read with key to notifications api","time":"2019-10-14T09:36:33.517Z","v":0}
{"name":"default-sharelatex","hostname":"8424a0b957cd","pid":469,"level":30,"key":"mongo.InstitutionsAPI.addAffiliation","args":{"0":"5da441a1d71baf01d58bd526"},"elapsedTime":28,"msg":"[Metrics] timed async method call","time":"2019-10-14T09:36:33.546Z","v":0}
{"name":"default-sharelatex","hostname":"8424a0b957cd","pid":469,"level":30,"user":{"__v":0,"_id":"5da441a1d71baf01d58bd526","thirdPartyIdentifiers":[],"samlIdentifiers":[],"awareOfV2":false,"betaProgram":false,"refered_user_count":0,"refered_users":[],"referal_id":"e8c56295","must_reconfirm":false,"features":{"trackChanges":true,"references":true,"templates":true,"compileGroup":"standard","compileTimeout":180,"gitBridge":true,"github":true,"dropbox":true,"versioning":true,"collaborators":-1},"ace":{"syntaxValidation":true,"pdfViewer":"pdfjs","spellCheckLanguage":"en","autoPairDelimiters":true,"autoComplete":true,"fontSize":12,"overallTheme":"","theme":"textmate","mode":"none"},"holdingAccount":false,"loginCount":0,"lastLoginIp":"","signUpDate":"2019-10-14T09:36:33.488Z","staffAccess":{"adminMetrics":false,"groupManagement":false,"groupMetrics":false,"institutionManagement":false,"institutionMetrics":false,"publisherManagement":false,"publisherMetrics":false},"isAdmin":false,"institution":"","role":"","first_name":"jow","emails":[{"_id":"5da441a1d71baf01d58bd527","createdAt":"2019-10-14T09:36:33.492Z","reversedHostname":"moc.tset","email":"jow@test.com"}],"email":"jow@test.com"},"msg":"registered","time":"2019-10-14T09:36:33.757Z","v":0}
{"name":"default-sharelatex","hostname":"8424a0b957cd","pid":469,"level":30,"data":{"expiresIn":604800},"expiresIn":3600,"token_start":"7fe09696","msg":"generating token for 5da441a1d71baf01d58bd526","time":"2019-10-14T09:36:33.770Z","v":0}

Successfully created jow@test.com as an admin user.

Please visit the following URL to set a password for jow@test.com and log in:

        http://localhost/user/password/set?passwordResetToken=7fe09696e1fab87d57c3a4412b12918389cde03cfd1031d39cef406734d0ba51

Done, without errors.

```

**Comment by wixaw** [comment]
I use a external mongodb, maybe could it be a link?

**Comment by msimonin** [comment]
My guess would be rather the nodejs version.

**Comment by wixaw** [comment]
Hum, if we have the same container, we should have the same version of nodejs .. no ?

**Comment by wixaw** [comment]
Hello @mserranom 
This not working with 2.0.1

cat docker-compose.yml

```
version: '2.2'
services:
    sharelatex:
        restart: always
        image: sharelatex/sharelatex:2.0.1
        container_name: sharelatex
        depends_on:
            redis:
                condition: service_started
        privileged: true
        ports:
            - 80:80
        links:
            - redis
        volumes:
            - /local/sharelatex:/var/lib/sharelatex
            - /local/sharelatex:/var/log/sharelatex:rw
            - /var/run/docker.sock:/var/run/docker.sock
        environment:

            SHARELATEX_APP_NAME: Overleaf (ex ShareLaTeX)

            SHARELATEX_MONGO_URL: mongodb://10.254.0.1/sharelatex

            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis

            ENABLED_LINKED_FILE_TYPES: 'url,project_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            ## Set for SSL via nginx-proxy
            #VIRTUAL_HOST: 103.112.212.22

            SHARELATEX_SITE_URL: http://hostname:5000
            SHARELATEX_NAV_TITLE: IRITeX
            SHARELATEX_HEADER_IMAGE_URL: https://www.domain.fr/favicons/android-chrome-192x192.png
            # SHARELATEX_ADMIN_EMAIL: support@it.com
            SHARELATEX_ADMIN_EMAIL: "Assistance IRIT"
            SHARELATEX_LEFT_FOOTER: '[{"text": "-"},{"text": "-"} ]'
            SHARELATEX_RIGHT_FOOTER: '[{"text": ":)"} ]'

            SHARELATEX_EMAIL_FROM_ADDRESS: "no-reply@domain.fr"

            # SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID:
            # SHARELATEX_EMAIL_AWS_SES_SECRET_KEY:

            SHARELATEX_EMAIL_SMTP_HOST: mailhost.irit.fr
            SHARELATEX_EMAIL_SMTP_PORT: 25
            # SHARELATEX_EMAIL_SMTP_SECURE: false
            # SHARELATEX_EMAIL_SMTP_USER:
            # SHARELATEX_EMAIL_SMTP_PASS:
            # SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
            # SHARELATEX_EMAIL_SMTP_IGNORE_TLS: false
            # SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by department x </div>"


    redis:
        restart: always
        image: redis
        container_name: redis
        expose:
            - 6379
        volumes:
            - ~/redis_data:/data
```



Logs up 

```
Creating redis ... done
Creating sharelatex ... done
Attaching to redis, sharelatex
redis         | 1:C 22 Oct 2019 11:26:06.777 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis         | 1:C 22 Oct 2019 11:26:06.777 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis         | 1:C 22 Oct 2019 11:26:06.777 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis         | 1:M 22 Oct 2019 11:26:06.778 * Running mode=standalone, port=6379.
redis         | 1:M 22 Oct 2019 11:26:06.778 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis         | 1:M 22 Oct 2019 11:26:06.778 # Server initialized
redis         | 1:M 22 Oct 2019 11:26:06.778 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis         | 1:M 22 Oct 2019 11:26:06.778 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis         | 1:M 22 Oct 2019 11:26:06.779 * DB loaded from disk: 0.000 seconds
redis         | 1:M 22 Oct 2019 11:26:06.779 * Ready to accept connections
sharelatex    | *** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
sharelatex    | *** Running /etc/my_init.d/00_regen_sharelatex_secrets.sh...
sharelatex    | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
sharelatex    | *** Running /etc/my_init.d/00_set_docker_host_ipaddress.sh...
sharelatex    | *** Running /etc/my_init.d/10_syslog-ng.init...
sharelatex    | Oct 22 11:26:07 ce578f48b016 syslog-ng[57]: syslog-ng starting up; version='3.13.2'
sharelatex    | *** Running /etc/my_init.d/98_check_db_access.sh...
sharelatex    | Checking can connect to mongo and redis
sharelatex    | Running "check:redis" task
sharelatex    | Checking can connect to redis
sharelatex    | node_redis: Warning: Redis server does not require a password, but a password was supplied.
sharelatex    | OK.
sharelatex    | Done, without errors.
sharelatex    | Running "check:mongo" task
sharelatex    | Checking can connect to mongoOK.
sharelatex    | Done, without errors.
sharelatex    | All checks passed
sharelatex    | *** Running /etc/my_init.d/99_migrate.sh...
sharelatex    | /usr/bin/node
sharelatex    | /usr/bin/grunt
sharelatex    | total 68
sharelatex    | drwxr-xr-x  2 www-data www-data  4096 Oct  8 13:24 .
sharelatex    | drwxr-xr-x 21 www-data www-data  4096 Oct  8 13:25 ..
sharelatex    | -rw-r--r--  1 www-data www-data  2911 Oct  8 13:24 10_update_project_tokens.js
sharelatex    | -rw-r--r--  1 www-data www-data  5031 Oct  8 13:24 1_move_doc_lines_to_doc_collection.coffee
sharelatex    | -rw-r--r--  1 www-data www-data  5936 Oct  8 13:24 2_doc_lines_delete_from_project.coffee
sharelatex    | -rw-r--r--  1 www-data www-data 10627 Oct  8 13:24 3_pack_docHistory_collection.coffee
sharelatex    | -rw-r--r--  1 www-data www-data   788 Oct  8 13:24 4_update_user_features.coffee
sharelatex    | -rw-r--r--  1 www-data www-data  3526 Oct  8 13:24 5_remove_holding_accounts.coffee
sharelatex    | -rw-r--r--  1 www-data www-data   652 Oct  8 13:24 6_add_track_changes_feature.coffee
sharelatex    | -rw-r--r--  1 www-data www-data  1334 Oct  8 13:24 7_add_token_indexes.coffee
sharelatex    | -rw-r--r--  1 www-data www-data   733 Oct  8 13:24 7_add_track_changes_feature_again.coffee
sharelatex    | -rw-r--r--  1 www-data www-data  1153 Oct  8 13:24 9_create_user_emails_array.js
sharelatex    | -rw-r--r--  1 www-data www-data   335 Oct  8 13:24 about_migrations.md
sharelatex    | Initializing
sharelatex    | Command-line options: --verbose, --gruntfile=/var/www/sharelatex/Gruntfile.coffee
sharelatex    | 
sharelatex    | Reading "Gruntfile.coffee" Gruntfile...OK
sharelatex    | 
sharelatex    | Registering Gruntfile tasks.
sharelatex    | 
sharelatex    | Registering "grunt-bunyan" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
sharelatex    | Loading "bunyan.js" tasks...OK
sharelatex    | + bunyan
sharelatex    | 
sharelatex    | Registering "grunt-execute" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
sharelatex    | Loading "execute.js" tasks...OK
sharelatex    | + execute
sharelatex    | 
sharelatex    | Registering "grunt-available-tasks" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
sharelatex    | Loading "available_tasks.js" tasks...OK
sharelatex    | + availabletasks
sharelatex    | 
sharelatex    | Registering "grunt-concurrent" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
sharelatex    | Loading "concurrent.js" tasks...OK
sharelatex    | + concurrent
sharelatex    | 
sharelatex    | Registering "grunt-contrib-coffee" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
sharelatex    | Loading "coffee.js" tasks...OK
sharelatex    | + coffee
sharelatex    | 
sharelatex    | Registering "grunt-shell" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
sharelatex    | Loading "shell.js" tasks...OK
sharelatex    | + shell
sharelatex    | 
sharelatex    | Registering "./tasks" tasks.
sharelatex    | Loading "CreateAndDestoryUsers.coffee" tasks...OK
sharelatex    | + user:create-admin, user:delete
sharelatex    | Loading "ProjectSize.coffee" tasks...OK
sharelatex    | >> No tasks were registered or unregistered.
sharelatex    | Initializing config...OK
sharelatex    | Loading "Gruntfile.coffee" tasks...OK
sharelatex    | + check, check:make, check:mongo, check:redis, default, help, install, install:all, install:chat, install:clsi, install:contacts, install:docstore, install:document-updater, install:filestore, install:notifications, install:real-time, install:spelling, install:tags, install:track-changes, install:web, migrate, postinstall, run, run:all, update, update:all
sharelatex    | 
sharelatex    | Running tasks: migrate
sharelatex    | 
sharelatex    | Running "migrate" task
sharelatex    | 
sharelatex    | Running "coffee:migrate" (coffee) task
sharelatex    | Verifying property coffee.migrate exists in config...OK
sharelatex    | Files: migrations/1_move_doc_lines_to_doc_collection.coffee -> migrations/1_move_doc_lines_to_doc_collection.js
sharelatex    | Files: migrations/2_doc_lines_delete_from_project.coffee -> migrations/2_doc_lines_delete_from_project.js
sharelatex    | Files: migrations/3_pack_docHistory_collection.coffee -> migrations/3_pack_docHistory_collection.js
sharelatex    | Files: migrations/4_update_user_features.coffee -> migrations/4_update_user_features.js
sharelatex    | Files: migrations/5_remove_holding_accounts.coffee -> migrations/5_remove_holding_accounts.js
sharelatex    | Files: migrations/6_add_track_changes_feature.coffee -> migrations/6_add_track_changes_feature.js
sharelatex    | Files: migrations/7_add_token_indexes.coffee -> migrations/7_add_token_indexes.js
sharelatex    | Files: migrations/7_add_track_changes_feature_again.coffee -> migrations/7_add_track_changes_feature_again.js
sharelatex    | Options: bare, join=false, sourceMap=false, joinExt=".src.coffee", separator="\n"
sharelatex    | Reading migrations/1_move_doc_lines_to_doc_collection.coffee...OK
sharelatex    | Writing migrations/1_move_doc_lines_to_doc_collection.js...OK
sharelatex    | Reading migrations/2_doc_lines_delete_from_project.coffee...OK
sharelatex    | Writing migrations/2_doc_lines_delete_from_project.js...OK
sharelatex    | Reading migrations/3_pack_docHistory_collection.coffee...OK
sharelatex    | Writing migrations/3_pack_docHistory_collection.js...OK
sharelatex    | Reading migrations/4_update_user_features.coffee...OK
sharelatex    | Writing migrations/4_update_user_features.js...OK
sharelatex    | Reading migrations/5_remove_holding_accounts.coffee...OK
sharelatex    | Writing migrations/5_remove_holding_accounts.js...OK
sharelatex    | Reading migrations/6_add_track_changes_feature.coffee...OK
sharelatex    | Writing migrations/6_add_track_changes_feature.js...OK
sharelatex    | Reading migrations/7_add_token_indexes.coffee...OK
sharelatex    | Writing migrations/7_add_token_indexes.js...OK
sharelatex    | Reading migrations/7_add_track_changes_feature_again.coffee...OK
sharelatex    | Writing migrations/7_add_track_changes_feature_again.js...OK
sharelatex    | 
sharelatex    | Running "shell:migrate" (shell) task
sharelatex    | Verifying property shell.migrate exists in config...OK
sharelatex    | File: [no files]
sharelatex    | Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
sharelatex    | Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://10.254.0.1/sharelatex
sharelatex    | nothing to migrate
sharelatex    | 
sharelatex    | Done, without errors.
sharelatex    | All migrations finished
sharelatex    | *** Booting runit daemon...
sharelatex    | *** Runit started as PID 116
sharelatex    | >> Setting permissions on docker socket
sharelatex    | Oct 22 11:26:10 ce578f48b016 cron[124]: (CRON) INFO (pidfile fd = 3)
sharelatex    | Oct 22 11:26:10 ce578f48b016 cron[124]: (CRON) INFO (Running @reboot jobs)

```

I have this same error : 
```
docker-compose exec sharelatex /bin/bash -c "cd /var/www/sharelatex; grunt user:create-admin --email=secondadmin@domain.fr"
Running "user:create-admin" task
using statsd
Set UV_THREADPOOL_SIZE=16
{"name":"default-sharelatex","hostname":"af6725dc742b","pid":448,"level":30,"msg":"Using newsletter provider: none","time":"2019-10-22T11:44:29.594Z","v":0}
{"name":"default-sharelatex","hostname":"af6725dc742b","pid":448,"level":30,"msg":"using smtp for email","time":"2019-10-22T11:44:29.867Z","v":0}
{"name":"default-sharelatex","hostname":"af6725dc742b","pid":448,"level":30,"key":"mongo.UserGetter.getUserByAnyEmail","args":{},"elapsedTime":26,"msg":"[Metrics] timed async method call","time":"2019-10-22T11:44:29.926Z","v":0}
Fatal error: user.save is not a function

```

Thanks you in advance
Will

**Comment by mserranom** [comment]
Hey @wixaw can you double check the user `secondadmin@domain.fr` doesn't already exist in the DB? (perhaps because you tried to create it with an error previously)

**Comment by wixaw** [comment]
@mserranom Arffffff !!! Yes it's work with an other email .... what an idiot not to have tested!
Sorry for the inconvenience...

**Pull request merged**
