### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by leo-022**
Here is my full translation into German.
Was standing: cb657d1f1cec7b3a80e56cf293773f91af91c943

## Description
new de.json
full translation into German

## Contributor Agreement

- [x] I confirm I have signed the [Contributor License Agreement](https://github.com/overleaf/overleaf/blob/master/CONTRIBUTING.md#contributor-license-agreement)

### CODE REVIEW

**Comment by jdleesmiller** [comment]
Thanks for the PR! @das7pad will have a look when current projects finish.

One item before then: I don't see your github username on the CLA list. Could you please try submitting the CLA again?

**Comment by leo-022** [comment]
I resubmitted CLA.

**Comment by gh2k** [comment]
Unfortunately, these changes are generated by our integration with the OneSky translation platform, which is where all of our translations are handled. @das7pad do you know if it's possible to export @leo-022's changes to there, so that we can re-import them?

**Comment by das7pad** [comment]
> Unfortunately, these changes are generated by our integration with the OneSky translation platform, which is where all of our translations are handled. @das7pad do you know if it's possible to export @leo-022's changes to there, so that we can re-import them?

We should be able to import these as mentioned on [Slack (internal)](https://digital-science.slack.com/archives/C20TZCMMF/p1661867653691209) a while back.

**Pull request closed without merging**
